# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 203)
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(300, 160, 75, 23))
        self.add.setObjectName("add")
        self.back = QtWidgets.QPushButton(Dialog)
        self.back.setGeometry(QtCore.QRect(130, 160, 75, 23))
        self.back.setObjectName("back")
        self.Name = QtWidgets.QLabel(Dialog)
        self.Name.setGeometry(QtCore.QRect(40, 30, 47, 13))
        self.Name.setObjectName("Name")
        self.Name_ed = QtWidgets.QLineEdit(Dialog)
        self.Name_ed.setGeometry(QtCore.QRect(30, 50, 81, 20))
        self.Name_ed.setObjectName("Name_ed")
        self.Sort_ed = QtWidgets.QLineEdit(Dialog)
        self.Sort_ed.setGeometry(QtCore.QRect(130, 50, 81, 20))
        self.Sort_ed.setObjectName("Sort_ed")
        self.Sort = QtWidgets.QLabel(Dialog)
        self.Sort.setGeometry(QtCore.QRect(160, 30, 47, 13))
        self.Sort.setObjectName("Sort")
        self.Roasting_ed = QtWidgets.QLineEdit(Dialog)
        self.Roasting_ed.setGeometry(QtCore.QRect(240, 50, 81, 20))
        self.Roasting_ed.setObjectName("Roasting_ed")
        self.Roasting = QtWidgets.QLabel(Dialog)
        self.Roasting.setGeometry(QtCore.QRect(260, 30, 47, 13))
        self.Roasting.setObjectName("Roasting")
        self.Grains_ed = QtWidgets.QLineEdit(Dialog)
        self.Grains_ed.setGeometry(QtCore.QRect(350, 50, 111, 20))
        self.Grains_ed.setObjectName("Grains_ed")
        self.Grains = QtWidgets.QLabel(Dialog)
        self.Grains.setGeometry(QtCore.QRect(390, 30, 47, 13))
        self.Grains.setObjectName("Grains")
        self.Description_ed = QtWidgets.QLineEdit(Dialog)
        self.Description_ed.setGeometry(QtCore.QRect(30, 110, 281, 20))
        self.Description_ed.setObjectName("Description_ed")
        self.Description = QtWidgets.QLabel(Dialog)
        self.Description.setGeometry(QtCore.QRect(140, 90, 61, 16))
        self.Description.setObjectName("Description")
        self.Cost_ed = QtWidgets.QLineEdit(Dialog)
        self.Cost_ed.setGeometry(QtCore.QRect(340, 110, 61, 20))
        self.Cost_ed.setObjectName("Cost_ed")
        self.Cost = QtWidgets.QLabel(Dialog)
        self.Cost.setGeometry(QtCore.QRect(360, 90, 47, 13))
        self.Cost.setObjectName("Cost")
        self.Volume_ed = QtWidgets.QLineEdit(Dialog)
        self.Volume_ed.setGeometry(QtCore.QRect(410, 110, 61, 20))
        self.Volume_ed.setObjectName("Volume_ed")
        self.Volume = QtWidgets.QLabel(Dialog)
        self.Volume.setGeometry(QtCore.QRect(420, 90, 47, 13))
        self.Volume.setObjectName("Volume")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add.setText(_translate("Dialog", "Add"))
        self.back.setText(_translate("Dialog", "Back"))
        self.Name.setText(_translate("Dialog", "Name"))
        self.Sort.setText(_translate("Dialog", "Sort"))
        self.Roasting.setText(_translate("Dialog", "Roasting"))
        self.Grains.setText(_translate("Dialog", "Grains"))
        self.Description.setText(_translate("Dialog", "Description"))
        self.Cost.setText(_translate("Dialog", "Сost"))
        self.Volume.setText(_translate("Dialog", "Volume"))
